function run_fixed60_phase40k()
% NEW CANDIDATE - NOT YET VERIFIED
% Single entry. Only 60.000 Hz, 30 seconds. Entire MATLAB folder is portable.
root_dir=fileparts(mfilename('fullpath'));addpath(root_dir);
outdir=fullfile(root_dir,'RESULTS',datestr(now,'yyyymmdd_HHMMSS'));
assert(~exist(outdir,'dir'),'Result directory exists; rerun after one second');mkdir(outdir);
statusfile=fullfile(outdir,'STATUS.txt');write_status(statusfile,'RUNNING - no integration result yet');
c=firmware_config();Fs=40000;Fpll=5000;duration=30;
tadc=(0:Fs*duration-1)'/Fs;adc=uint16(round(2048+1860*sin(2*pi*60*tadc)));
fprintf('Running unchanged Fixed60Hz model: 60.000 Hz, 30 seconds...\n');
[r,pdiag]=stage17_model_60hz(adc,'locked_fixed_60');
% Capture the original PRE-update theta at raw ADC index 8*n, t=(8*n-1)/40k.
% No 25-us compensation, detector compensation, or extra output phase offset.
anchors=pdiag(:,4);steps=r(:,12);valid=r(:,2)~=0;
d=phase_delivery_8tick(anchors,steps,valid,c.full);
% Last anchor has only 1 observed tick before 30 seconds. Exclude its 7 future
% predicted samples and its unobserved full-interval residual from statistics.
trace=d.trace(1:end-7,:);d=rmfield(d,'trace');
t=tadc(8:end);clear tadc adc
N=numel(anchors);idx=repelem((1:N)',8);idx=idx(1:end-7);M=d.modulus;
held=anchors(idx)*8;theta=trace(:,2);oracle=mod(held+trace(:,9).*steps(idx),M);
held_ref=sine_q15_ticks(held,M,c.sin);extrapolated_ref=sine_q15_ticks(theta,M,c.sin);
nominal_hz=double(c.nom)*Fpll/double(c.full);
firsthold=find(pdiag(:,1)~=0,1);
vectors=check_delivery_vectors(c);writetable(vectors,fullfile(outdir,'delivery_vector_checks.csv'));
assert(~isempty(firsthold),'HOLD never entered: no integration qualification');
anchor_t=((1:N)'*8-1)/Fs;hold_t=anchor_t(firsthold);
assert(t(end)-hold_t>=20,'Less than 20 seconds observed after first HOLD');
% Exactly the SAME 20 s / 1200 grid cycles for both metrics. Start >=1s after
% first HOLD and align to a GRID cycle, not separately to either reference.
start_time=ceil((hold_t+1)*60)/60;
i0=find(t>=start_time,1);window=(i0:i0+20*Fs-1)';
assert(~isempty(i0) && window(end)<=numel(t),'30 seconds insufficient for requested steady window');
complete=(1:N-1)';iv=complete(valid(complete));
steady_intervals=iv(anchor_t(iv)>=t(window(1)) & anchor_t(iv)+1/Fpll<=t(window(end)));
assert(~isempty(steady_intervals));
post=(firsthold:N)';postticks=find(idx>=firsthold);
delta=[int64(0);circular(diff(theta),M)];
reset_residual=[int64(0);circular(diff(theta)-trace(1:end-1,10),M)];
held_delta=[int64(0);circular(diff(held),M)];
boundary=trace(:,9)==0;
bwin=window(boundary(window));bwin=bwin(bwin>1);
[mheld,sheld,zheld]=reference_metrics(t(window),held(window),held_ref(window),held_delta(bwin),M);
[mext,sext,zext]=reference_metrics(t(window),theta(window),extrapolated_ref(window),reset_residual(bwin),M);
metric_names={'Fundamental frequency (Hz)';'RMS phase error (deg)';'Peak phase error (deg)';...
 'Positive ZC RMS error (us)';'Negative ZC RMS error (us)';'THD H2-H40 (%)';...
 'Below 20kHz nonfundamental RMS / fundamental (%)';'Max anchor discontinuity (deg)'};
writetable(table(metric_names,mheld,mext,'VariableNames',{'Metric','Held5k','Extrapolated40k'}),...
 fullfile(outdir,'reference_metrics.csv'));
flag_metrics=table({'phase_ok uptime (%)';'phase_ok drop count';'locked uptime (%)';'lock loss count'},...
 [100*mean(r(post,14)~=0);sum(diff(double(r(post,14)))==-1);...
 100*mean(r(post,15)~=0);sum(diff(double(r(post,15)))==-1)],'VariableNames',{'Metric','AfterFirstHold'});
writetable(flag_metrics,fullfile(outdir,'pll_flags.csv'));
% Mathematical increment deviation: observed phase increment minus PREVIOUS
% row's exact base. The first global row has no observed predecessor.
deviation=delta(window)-trace(window-1,3);
res=double(d.interval(steady_intervals,3))*360/double(M);
offset=circular(theta(window)-oracle(window),M);
phase_post=unwrap(double(r(post,13))*2*pi/double(c.full))*180/pi;
input_post=360*60*(anchor_t(post)+1/Fpll);
phase_drift=phase_post-input_post;
fit=polyfit(anchor_t(post)-anchor_t(post(1)),phase_drift,1);
phase_lsb=360/double(M);elapsed=anchor_t(end)-hold_t;
smooth_h=max(abs(diff(double(held_ref(window)))));
smooth_e=max(abs(diff(double(extrapolated_ref(window)))));
increment_bound=idivide(abs(trace(window-1,4))+7,int64(8),'floor');
measurements=table({'Max instantaneous phase increment deviation (deg)';...
 'Max absolute anchor residual (deg)';'RMS anchor residual (deg)';'Mean anchor residual (deg)';...
 'Mean added phase offset versus same-time PLL ramp (deg)';'Max added phase offset (deg)';...
 'Post-HOLD PLL drift (deg/s)';'Expected nominal quantization drift (deg/s)';...
 'Held max adjacent reference change (Q15 counts)';'Extrapolated max adjacent change (Q15 counts)'},...
 [max(abs(double(deviation)))*phase_lsb;max(abs(res));sqrt(mean(res.^2));mean(res);...
 mean(double(offset))*phase_lsb;max(abs(double(offset)))*phase_lsb;fit(1);...
 (nominal_hz-60)*360;smooth_h;smooth_e],'VariableNames',{'Metric','Value'});
writetable(measurements,fullfile(outdir,'delivery_metrics.csv'));
checks=table({'At least 20 seconds after FIRST HOLD';'phase_ok always 1 after HOLD';...
 'locked always 1 after HOLD';'Every actual PLL step nominal after HOLD';'No return to TRACK';...
 'Slow error within existing off threshold';'PLL HOLD entry has no integration jump';...
 'No phase reset on any valid anchor';'Every complete interval sums correction exactly';...
 'Every complete interval endpoint residual exactly zero';'No residual correction after eighth tick';...
 'Signed/wrap/fractional-base synthetic vectors';'All output phases wrapped';...
 'Same-time steady phase matches oracle within one Q24 LSB';'No fixed one-tick latency';...
 'Extrapolated reference has smaller max adjacent change';'No abnormal single-tick increment';...
 'Only nominal quantization drift remains'},...
 [elapsed>=20;all(r(post,14)==1);all(r(post,15)==1);all(steps(post)==c.nom);...
 all(pdiag(post,1)==1);all(abs(r(post,7))<=45);pdiag(firsthold,5)==0;...
 all(reset_residual(boundary & valid(idx))==0);...
 all(d.interval(iv,1)==d.interval(iv,2));all(d.interval(iv,3)==0);...
 all(trace(trace(:,9)==7,8)==0);all(vectors.Satisfied);...
 all(theta>=0 & theta<M);all(abs(offset)<=1);...
 all(abs(offset)<=1) && vectors.Satisfied(end);smooth_e<smooth_h;...
 all(abs(deviation)<=increment_bound+1);...
 abs(fit(1)-(nominal_hz-60)*360)<=8*phase_lsb/max(elapsed,1)],...
 'VariableNames',{'Check','Satisfied'});
writetable(checks,fullfile(outdir,'integration_checks.csv'));disp(checks);
% Every boundary is retained; selected event groups also get independent reports/zooms.
events={bwin;window(find(extrapolated_ref(window(1:end-1))<0 & extrapolated_ref(window(2:end))>=0)+1);...
 window(find(extrapolated_ref(window(1:end-1))>0 & extrapolated_ref(window(2:end))<=0)+1);...
 window(abs(double(extrapolated_ref(window)))>=32760);...
 window(find(diff(double(theta(window)))< -double(M)/2)+1)};
event_names={'5k boundary';'positive ZC';'negative ZC';'sine peaks';'359.x to 0.x wrap'};
counts=zeros(5,1);maxjump=zeros(5,1);
for k=1:5,counts(k)=numel(events{k});assert(counts(k)>0,'Missing event coverage');
 maxjump(k)=max(abs(double(reset_residual(events{k}))))*phase_lsb;end
writetable(table(event_names,counts,maxjump,'VariableNames',{'Event','Count','MaxIntegrationResidual_deg'}),...
 fullfile(outdir,'event_coverage.csv'));
writetable(array2table([anchor_t(complete) double(d.interval(complete,:))],...
 'VariableNames',{'anchor_time_s','error_ticks','sum_correction_ticks','endpoint_residual_ticks','theta_start_ticks','theta_end_ticks'}),...
 fullfile(outdir,'anchor_intervals.csv'));
debug=array2table([t double(trace) double(pdiag(idx,1)) double(r(idx,14:15)) double(held_ref) double(extrapolated_ref)],...
 'VariableNames',[{'time_s'} d.names {'HOLD_60HZ','phase_ok','locked','held_ref_q15','extrapolated_ref_q15'}]);
writetable(debug,fullfile(outdir,'debug_40k.csv'));clear debug
writetable(array2table([anchor_t double(r) double(pdiag(:,1))],'VariableNames',[{'time_s'} c.names {'HOLD_60HZ'}]),...
 fullfile(outdir,'pll_5k.csv'));
writetable(sheld,fullfile(outdir,'spectrum_held.csv'));writetable(sext,fullfile(outdir,'spectrum_extrapolated.csv'));
plot_fixed60_integration(outdir,t,r,idx,held,theta,held_ref,extrapolated_ref,trace,window,events,c,sheld,sext);
save(fullfile(outdir,'integration_data.mat'),'r','pdiag','t','trace','held_ref','extrapolated_ref',...
 'window','checks','measurements','zheld','zext','-v7.3');
if all(checks.Satisfied)
 result='MATLAB INTEGRATION CANDIDATE CHECKS SATISFIED - not Verilog or SIMPLIS PASS';
else,result='MATLAB INTEGRATION NOT QUALIFIED - inspect integration_checks.csv';end
write_status(statusfile,sprintf('%s\nExecuted %s\nWindow %.9f to %.9f s, N=%d\nNominal %.12f Hz\nNEW CANDIDATE - no HDL or hardware validation\n',...
 result,datestr(now,30),t(window(1)),t(window(end)),numel(window),nominal_hz));
disp(result);fprintf('Results: %s\n',outdir);
end
function e=circular(x,M)
e=mod(x+idivide(M,int64(2)),M)-idivide(M,int64(2));
end
function write_status(path,s)
fid=fopen(path,'w');assert(fid>=0);closer=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',s);
end
